using System.Collections.Generic;
using System.Linq;
using System.Text;

using Netor.Cortana.Plugin.Process.Generator.Analysis;

namespace Netor.Cortana.Plugin.Process.Generator.Emitters;

/// <summary>
/// 生成 Program.g.cs：插件元数据、工具路由字典、DI 注册委托、消息循环入口。
/// <para>
/// 生成后的 <c>Program</c> partial 类暴露 <c>RunPluginAsync()</c> 方法，
/// 用户 Main 方法调用该方法即可启动标准插件循环；
/// Debugger 通过 <c>RunPluginAsync(TextReader, TextWriter)</c> 重载
/// 在内存管道上驱动同一消息循环，确保测试路径与生产路径一致。
/// </para>
/// </summary>
internal static class ProgramEmitter
{
    public static string Emit(PluginClassInfo plugin, List<ToolClassInfo> toolClasses)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 由 Netor.Cortana.Plugin.Process.Generator 自动生成");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Netor.Cortana.Plugin.Process.Hosting;");
        sb.AppendLine("using Netor.Cortana.Plugin.Process.Protocol;");
        sb.AppendLine();

        if (plugin.Namespace != null)
        {
            sb.AppendLine($"namespace {plugin.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {plugin.ClassName}");
        sb.AppendLine("{");

        EmitInfoField(sb, plugin, toolClasses);
        EmitRegisterTools(sb, toolClasses);
        EmitInvokers(sb, toolClasses);
        EmitRunAsync(sb, plugin);

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>生成静态 <c>s_info</c> 字段（PluginInfoData）。</summary>
    private static void EmitInfoField(StringBuilder sb, PluginClassInfo plugin, List<ToolClassInfo> toolClasses)
    {
        sb.AppendLine("    /// <summary>插件静态元数据（由 [Plugin] 和 [Tool] 提取）。</summary>");
        sb.AppendLine("    private static readonly global::Netor.Cortana.Plugin.Process.Protocol.PluginInfoData s_info = new()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Id = {EscapeStringLiteral(plugin.Id)},");
        sb.AppendLine($"        Name = {EscapeStringLiteral(plugin.Name)},");
        sb.AppendLine($"        Version = {EscapeStringLiteral(plugin.Version)},");
        sb.AppendLine($"        Description = {EscapeStringLiteral(plugin.Description)},");
        if (plugin.Instructions != null)
            sb.AppendLine($"        Instructions = {EscapeStringLiteral(plugin.Instructions)},");
        if (plugin.Tags.Length > 0)
        {
            var tags = string.Join(", ", plugin.Tags.Select(EscapeStringLiteral));
            sb.AppendLine($"        Tags = new string[] {{ {tags} }},");
        }
        sb.AppendLine("        Tools = new global::Netor.Cortana.Plugin.Process.Protocol.ToolInfoData[]");
        sb.AppendLine("        {");
        foreach (var toolClass in toolClasses)
        {
            foreach (var method in toolClass.Methods)
            {
                sb.AppendLine("            new()");
                sb.AppendLine("            {");
                sb.AppendLine($"                Name = {EscapeStringLiteral(method.FullToolName)},");
                sb.AppendLine($"                Description = {EscapeStringLiteral(method.Description)},");
                if (method.Parameters.Count > 0)
                {
                    sb.AppendLine("                Parameters = new global::Netor.Cortana.Plugin.Process.Protocol.ParameterInfoData[]");
                    sb.AppendLine("                {");
                    foreach (var p in method.Parameters)
                    {
                        sb.AppendLine("                    new()");
                        sb.AppendLine("                    {");
                        sb.AppendLine($"                        Name = {EscapeStringLiteral(p.JsonName)},");
                        sb.AppendLine($"                        Type = {EscapeStringLiteral(p.JsonType)},");
                        sb.AppendLine($"                        Description = {EscapeStringLiteral(p.Description)},");
                        sb.AppendLine($"                        Required = {(p.Required ? "true" : "false")},");
                        sb.AppendLine("                    },");
                    }
                    sb.AppendLine("                },");
                }
                sb.AppendLine("            },");
            }
        }
        sb.AppendLine("        },");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    /// <summary>生成 <c>RegisterTools</c> 方法（AOT 安全，使用泛型 AddScoped）。</summary>
    private static void EmitRegisterTools(StringBuilder sb, List<ToolClassInfo> toolClasses)
    {
        sb.AppendLine("    /// <summary>Generator 生成：使用泛型注册所有工具类为 Scoped。</summary>");
        sb.AppendLine("    private static void RegisterTools(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var toolClass in toolClasses)
        {
            var fullName = toolClass.ClassSymbol.ToDisplayString();
            sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::{fullName}>(services);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>生成 <c>s_invokers</c> 工具路由字典。</summary>
    private static void EmitInvokers(StringBuilder sb, List<ToolClassInfo> toolClasses)
    {
        sb.AppendLine("    /// <summary>Generator 生成：工具名 → 调用委托（从 JsonElement 解析参数 → 调用工具方法 → 返回字符串结果）。</summary>");
        sb.AppendLine("    private static readonly global::System.Collections.Generic.Dictionary<string, global::Netor.Cortana.Plugin.Process.Hosting.ToolInvoker> s_invokers = new()");
        sb.AppendLine("    {");
        foreach (var toolClass in toolClasses)
        {
            foreach (var method in toolClass.Methods)
                EmitInvokerEntry(sb, toolClass, method);
        }
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitInvokerEntry(StringBuilder sb, ToolClassInfo toolClass, ToolMethodInfo method)
    {
        var fullClassName = toolClass.ClassSymbol.ToDisplayString();
        sb.AppendLine($"        [{EscapeStringLiteral(method.FullToolName)}] = async (sp, args) =>");
        sb.AppendLine("        {");

        foreach (var p in method.Parameters)
        {
            var parseExpr = TypeMapper.GetJsonParseExpression(p.TypeSymbol, $"args.GetProperty(\"{p.JsonName}\")");
            sb.AppendLine($"            var {p.CodeParamName} = {parseExpr};");
        }

        sb.AppendLine($"            var tool = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::{fullClassName}>(sp);");

        var callArgs = string.Join(", ", method.Parameters.Select(p => p.CodeParamName));
        var callExpr = $"tool.{method.MethodName}({callArgs})";

        if (method.IsAsync)
        {
            if (method.AsyncInnerType == null)
            {
                // Task / ValueTask
                if (method.IsValueTask)
                    sb.AppendLine($"            await {callExpr}.ConfigureAwait(false);");
                else
                    sb.AppendLine($"            await {callExpr}.ConfigureAwait(false);");
                sb.AppendLine("            return \"ok\";");
            }
            else
            {
                if (method.IsValueTask)
                    sb.AppendLine($"            var result = await {callExpr}.ConfigureAwait(false);");
                else
                    sb.AppendLine($"            var result = await {callExpr}.ConfigureAwait(false);");
                var convert = TypeMapper.GetReturnConvertExpression(method.AsyncInnerType, "result");
                sb.AppendLine($"            return {convert};");
            }
        }
        else
        {
            if (TypeMapper.IsVoid(method.ReturnType))
            {
                sb.AppendLine($"            {callExpr};");
                sb.AppendLine("            return \"ok\";");
            }
            else
            {
                sb.AppendLine($"            var result = {callExpr};");
                var convert = TypeMapper.GetReturnConvertExpression(method.ReturnType, "result");
                sb.AppendLine($"            return {convert};");
            }
        }
        sb.AppendLine("        },");
    }

    /// <summary>生成 <c>RunPluginAsync</c> 入口方法（两个重载）。</summary>
    private static void EmitRunAsync(StringBuilder sb, PluginClassInfo plugin)
    {
        // 无参重载：用 Console.In/Out
        sb.AppendLine("    /// <summary>启动插件消息循环，从 stdin 读取请求，向 stdout 写响应。</summary>");
        sb.AppendLine("    internal static global::System.Threading.Tasks.Task RunPluginAsync()");
        sb.AppendLine("        => RunPluginAsync(global::System.Console.In, global::System.Console.Out);");
        sb.AppendLine();

        // 带参重载：Debugger 用内存管道调用此方法
        sb.AppendLine("    /// <summary>启动插件消息循环，使用自定义输入输出流（用于内存管道调试）。</summary>");
        sb.AppendLine("    internal static global::System.Threading.Tasks.Task RunPluginAsync(");
        sb.AppendLine("        global::System.IO.TextReader input,");
        sb.AppendLine("        global::System.IO.TextWriter output)");
        sb.AppendLine("        => global::Netor.Cortana.Plugin.Process.Hosting.ProcessPluginHost.RunAsync(");
        sb.AppendLine("            s_info,");
        sb.AppendLine("            s_invokers,");
        if (plugin.HasConfigureMethod)
            sb.AppendLine("            Configure,");
        else
            sb.AppendLine("            null,");
        sb.AppendLine("            RegisterTools,");
        sb.AppendLine("            input,");
        sb.AppendLine("            output);");
    }

    /// <summary>把字符串编码为 C# 字符串字面量（含双引号）。</summary>
    private static string EscapeStringLiteral(string s)
    {
        var sb = new StringBuilder(s.Length + 2);
        sb.Append('"');
        foreach (var ch in s)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"':  sb.Append("\\\""); break;
                case '\r': sb.Append("\\r");  break;
                case '\n': sb.Append("\\n");  break;
                case '\t': sb.Append("\\t");  break;
                default:
                    if (ch < 0x20) sb.Append($"\\u{(int)ch:X4}");
                    else sb.Append(ch);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
